name: publish-prerelease
on:
  workflow_dispatch:
    inputs:
      pre-release-tag:
        description: 'The pre-release tag use in the version'
        required: false
        default: 'pre'
      dist-tag:
        description: 'The dist-tag use'
        required: false
        default: 'next'

jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: |
          npm install
          npm test
      - name: Update your package.json with an npm pre-release version
        id: pre-release-version
        uses: adobe/update-prerelease-npm-version@v1.0.2
        with:
          pre-release-tag: ${{ github.event.inputs.pre-release-tag }}
          dependencies-to-update-version-tag: ${{ github.event.inputs.dist-tag }}
      - run: echo pre-release-version - ${{ steps.pre-release-version.outputs.pre-release-version }}           
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
          tag: ${{ github.event.inputs.dist-tag }}
          access: 'public'
